var graystyles = {
    "grid": {
    },
    "panel": {
    },
    "groupPanel": {
        "background": "#ffa2a2a2",
        "paddingRight": "2",
        "iconLocation": "leftSide",
        "border": "#808080,1",
        "selectedForeground": "#ffffffff",
        "iconAlignment": "center",
        "foreground": "#ffffffff",
        "inactiveForeground": "#ff808080",
        "borderBottom": "#a0a0a0,1",
        "textAlignment": "near",
        "selectedBackground": "#ff696969",
        "lineAlignment": "center",
        "inactiveBackground": "#ffd3d3d3",
        "iconOffset": "0",
        "iconPadding": "0",
        "contentFit": "auto",
        "paddingTop": "4",
        "borderRight": "#ff777777,1",
        "shapeBackground": "#ff008800",
        "paddingBottom": "5",
        "iconIndex": "0",
        "head": {
            "borderRight": "#a0a0a0,1",
            "inner": {
                "borderTop": null,
                "borderRight": null
            }
        },
        "color": "#000",
        "item": {
            "background" : "#cccccc",
            "borderRight": "#a0a0a0,1",
            "inner": {
                "borderRight":null
            }
        },

    },
    "body": {
        "background": "#ffffffff",
        "foreground": "#ff202020",
        "iconLocation": "leftSide",
        //"border": "#ff313539,1",
        "iconAlignment": "center",
        "borderBottom": "#ffdedede,1",
        "iconPadding": "2",
        "selectedBackground": "#ff696969",
        "contentFit": "auto",
        "inactiveBackground": "#ffd3d3d3",
        "iconOffset": "0",
        "paddingRight": "2",
        "paddingBottom": "2",
        "paddingTop": "2",
        "shapeBackground": "#ff008800",
        "selectedForeground": "#ffffffff",
        "inactiveForeground": "#ff808080",
        "line": "#ff808080,1",
        "textAlignment": "near",
        "lineAlignment": "center",
        "borderRight": "#ffdedede,1",
        "iconIndex": "0",
        "empty": {},
        "row" : {
            "borderBottom": null
        }
    },
    "fixed": {
        "background": "#fff8f8f8",
        "paddingRight": "2",
        "iconLocation": "leftSide",
        "selectedForeground": "#ffffffff",
        "iconAlignment": "center",
        "foreground": "#ff000000",
        "inactiveForeground": "#ff808080",
        "borderBottom": "#ff909090,1",
        //"textAlignment": "right",
        "selectedBackground": "#ff696969",
        "lineAlignment": "center",
        "inactiveBackground": "#ffd3d3d3",
        "iconOffset": "0",
        "iconPadding": "0",
        "contentFit": "auto",
        "paddingTop": "2",
        "borderRight": "#ff909090,1",
        "shapeBackground": "#ff008800",
        "paddingBottom": "2",
        "iconIndex": "0",
        "columnBar": {
            "background": "#ffcccccc",
            "paddingRight": "2",
            "iconLocation": "leftSide",
            "border": "#ff313539,1",
            "selectedForeground": "#ffffffff",
            "iconAlignment": "center",
            "foreground": "#ff000000",
            "inactiveForeground": "#ff808080",
            "borderBottom": "#ff808080,1",
            "textAlignment": "center",
            "selectedBackground": "#ff696969",
            "lineAlignment": "center",
            "inactiveBackground": "#ffd3d3d3",
            "iconOffset": "0",
            "iconPadding": "0",
            "contentFit": "auto",
            "paddingTop": "2",
            "borderRight": "#ff808080,1",
            "shapeBackground": "#ff008800",
            "paddingBottom": "2",
            "iconIndex": "0"
        },
        "rowBar": {
            "background": "#ffd3d3d3",
            "paddingRight": "2",
            "iconLocation": "leftSide",
            "border": "#88888888,1",
            "selectedForeground": "#ffffffff",
            "iconAlignment": "center",
            "foreground": "#ff000000",
            "inactiveForeground": "#ff808080",
            "borderBottom": "#ff999999,1",
            "textAlignment": "center",
            "selectedBackground": "#ff696969",
            "lineAlignment": "center",
            "inactiveBackground": "#ffd3d3d3",
            "iconOffset": "0",
            "iconPadding": "0",
            "contentFit": "auto",
            "paddingTop": "2",
            "borderRight": "#ff999999,1",
            "shapeBackground": "#ff008800",
            "paddingBottom": "2",
            "iconIndex": "0"
        }
    },
    "header": {
        "background": "#484848",
        "color": "#fff",
        "borderBottom": "#ffa0a0a0,1",
        "borderRight": "#ffa0a0a0,1",
        "borderTop": "#ffffff,0",
        "selectedBackground": "#cccccc",
        "hoveredBackground": "#2b2b2b",
        "hoveredColor": "#ffffff",
        "group": {
            "background": "#484848",
            "selectedBackground": "#2b2b2b",
            "fontBold": "true",
            "color": "#fff",
            "selectedForeground": "#ff333333",

            "borderBottom": "#ffa0a0a0,1",
            "borderRight": "#ffa0a0a0,1",
            "borderTop": "#ffffff,0",
            "hoveredBackground": "#2b2b2b",
            "hoveredColor": "#ffffff",

            "iconLocation": "leftSide",
            "border": "#ff313539,1",
            "iconAlignment": "center",
            "contentFit": "auto",
            "inactiveBackground": "#ffd3d3d3",
            "iconOffset": "0",
            "iconPadding": "0",
            "shapeBackground": "#ff008800",
            "paddingBottom": "2",
            "paddingTop": "2",
            "paddingRight": "2",
            "inactiveForeground": "#ff808080",
            "textAlignment": "center",
            "lineAlignment": "center",
            "iconIndex": "0"
        }
    },
    "footer": {
        "background": "#eef0f4",
        "foreground": "#000000",
        "borderTop": "#a0a0a0,1",
        "borderLeft": "#ffffffff,1",
        "borderRight": "#ffa0a0a0,1",

        "iconLocation": "leftSide",
        "border": "#88888888,1",
        "iconAlignment": "center",
        "iconOffset": "0",
        "selectedBackground": "#ff696969",
        "contentFit": "auto",
        "inactiveBackground": "#ffd3d3d3",
        "iconPadding": "0",
        "paddingRight": "2",
        "paddingBottom": "1",
        "paddingTop": "2",
        "shapeBackground": "#ff008800",
        "selectedForeground": "#ffffffff",
        "inactiveForeground": "#ff808080",
        "textAlignment": "far",
        "lineAlignment": "center",
        "iconIndex": "0",
        "head": {
            "textAlignment": "center"
        }
    },
    "rowGroup": {
        "header": {
            "background": "#ffa2a2a2",
            "color": "#fff",
            "shapeBackground": "#ff003f4f",

            "borderBottom": "#ff888888",
            "borderTop": null,
            "borderRight": null,

            "iconLocation": "leftSide",
            "border": "#ff313539,0",
            "iconAlignment": "center",
            "selectedBackground": "#ff696969",
            "contentFit": "auto",
            "inactiveBackground": "#ffd3d3d3",
            "iconOffset": "0",
            "iconPadding": "0",
            "shapeBackground": "#ff008800",
            "paddingBottom": "2",
            "paddingTop": "2",
            "paddingRight": "2",
            "selectedForeground": "#ffffffff",
            "inactiveForeground": "#ff808080",
            "textAlignment": "near",
            "lineAlignment": "center",
            "iconIndex": "0"
        },
        "expander": {
            "borderRight": null,
            "shapeColor": "#fff"
        },
        "footer": {
            "background": "#cccccc",
            "foreground": "#000000",
            "borderTop": null,//"#a0a0a0,1",
            "borderBottom": "#999999,1",
            "borderLeft": "#ffffffff,0",
            "borderRight": "#999999,1",

            "iconLocation": "leftSide",
            "border": "#ffffffff,0",
            "iconAlignment": "center",
            "selectedBackground": "#ff696969",
            "contentFit": "auto",
            "inactiveBackground": "#ffd3d3d3",
            "iconOffset": "0",
            "iconPadding": "0",
            "shapeBackground": "#ff008800",
            "paddingBottom": "2",
            "paddingTop": "2",
            "paddingRight": "4",
            "selectedForeground": "#ffffffff",
            "inactiveForeground": "#ff808080",
            "textAlignment": "far",
            "lineAlignment": "center",
            "iconIndex": "0"
        },
        "head": {
            "background": "#484848",
            "borderBottom": "#a0a0a0,1",
            "borderRight": "#a0a0a0,1",
            "borderTop": "#ff349cde,0",
            "borderLeft": "#ffffffff,0",

            "iconLocation": "leftSide",
            "border": "#ff313539,1",
            "iconAlignment": "center",
            "selectedBackground": "#ffff0000",
            "contentFit": "auto",
            "inactiveBackground": "#ffd3d3d3",
            "iconOffset": "0",
            "selectionDisplay": "inversion",
            "iconPadding": "0",
            "shapeBackground": "#ff000000",
            "paddingBottom": "2",
            "paddingTop": "2",
            "paddingRight": "2",
            "selectedForeground": "#ffff0000",
            "foreground": "#ff002f6e",
            "inactiveForeground": "#ff808080",
            "textAlignment": "center",
            "lineAlignment": "center",
            "iconIndex": "0"
        },
        "foot": {
            "background2": "#ffdee2e7",
            "foreground2": "#ff000000",
            "borderTop2": "#ff79828b,1",
            "borderRight2": "#ff9099a3,1",

            "background": "#eef0f4",
            "foreground": "#000000",
            "borderTop": "#a0a0a0,1",
            "borderLeft": "#ffffffff,0",
            "borderRight": "#ffa0a0a0,1",

            "paddingRight": "2",
            "iconLocation": "leftSide",
            "border": "#88888888,1",
            "selectedForeground": "#ffffffff",
            "iconAlignment": "center",
            "inactiveForeground": "#ff808080",
            "iconOffset": "0",
            "textAlignment": "near",
            "selectedBackground": "#ff696969",
            "lineAlignment": "center",
            "inactiveBackground": "#ffd3d3d3",
            "contentFit": "auto",
            "paddingTop": "2",
            "shapeBackground": "#ff008800",
            "iconPadding": "0",
            "paddingBottom": "1",
            "iconIndex": "0"
        },
        "headerBar": {
            "background": "#ffd7e6f7",
            "iconLocation": "leftSide",
            "border": "#ffffffff,0",
            "iconAlignment": "center",
            "borderBottom": "#ffffffff,0",
            "borderTop": "#ffffffff,1",
            "selectedBackground": "#ff696969",
            "contentFit": "auto",
            "inactiveBackground": "#ffd3d3d3",
            "iconOffset": "0",
            "iconPadding": "0",
            "shapeBackground": "#ff498ee1",
            "paddingBottom": "2",
            "paddingTop": "2",
            "paddingRight": "2",
            "selectedForeground": "#ffffffff",
            "foreground": "#ff002f6e",
            "inactiveForeground": "#ff808080",
            "textAlignment": "near",
            "borderLeft": "#ffffffff,1",
            "lineAlignment": "center",
            "borderRight": "#ffffffff,0",
            "iconIndex": "0"
        },
        "footerBar": {
            "background": "#ff9cbade",
            "iconLocation": "leftSide",
            "border": "#ffffffff,0",
            "iconAlignment": "center",
            "borderBottom": "#ffffffff,0",
            "borderTop": "#ffd7e6f7,1",
            "selectedBackground": "#ff696969",
            "contentFit": "auto",
            "inactiveBackground": "#ffd3d3d3",
            "iconOffset": "0",
            "iconPadding": "0",
            "shapeBackground": "#ff008800",
            "paddingBottom": "2",
            "paddingTop": "2",
            "paddingRight": "2",
            "selectedForeground": "#ffffffff",
            "foreground": "#ff000000",
            "inactiveForeground": "#ff808080",
            "textAlignment": "near",
            "borderLeft": "#ffffffff,0",
            "lineAlignment": "center",
            "borderRight": "#ffd7e6f7,1",
            "iconIndex": "0"
        },
        "indent": {
            "background": "#a2a2a2",
            "borderRight": "#999999, 1",
            "borderBottom": "#999999, 1"
        }
    },
    "rowIndicator": {
        "background": "#ffa2a2a2",
        "color": "#ff000000",
        "hoveredBackground": "#205292f8",
        "selectedBackground": "#e5e5e5",
        "selectedColor": "#ff000000",
        "shapeBackground": "#000088",
        "borderLeft": "#ff333333,0",
        "borderBottom": "#ffbbbbbb,1",
        "borderTop": "#ff4dadee,0",

        "iconLocation": "leftSide",
        "border": "#ff313539,1",
        "iconAlignment": "center",
        "contentFit": "auto",
        "inactiveBackground": "#ffd3d3d3",
        "iconOffset": "0",
        "iconPadding": "0",
        "paddingBottom": "2",
        "paddingTop": "2",
        "paddingRight": "2",
        "inactiveForeground": "#ff808080",
        "textAlignment": "center",
        "lineAlignment": "center",
        "iconIndex": "0",
        "state": {
            "background2": "#ffffffff",
            "background": "#f8f8f8",
            "paddingRight": "2",

            "iconLocation": "leftSide",
            "border": "#ff313539,1",
            "selectedForeground": "#ffffffff",
            "iconAlignment": "center",
            "foreground": "#ff000000",
            "inactiveForeground": "#ff808080",
            "borderBottom": "#ffaab1b8,1",
            "textAlignment": "center",
            "selectedBackground": "#ff696969",
            "lineAlignment": "center",
            "inactiveBackground": "#ffd3d3d3",
            "iconOffset": "0",
            "iconPadding": "0",
            "contentFit": "auto",
            "paddingTop": "2",
            "borderRight": "#ffaab1b8,1",
            "shapeBackground": "#ff008800",
            "paddingBottom": "2",
            "iconIndex": "0"
        }
    },
    "checkBar": {
        "background": "#ffffffff",
        "borderRight": "#ffa0a0a0,1",
        "borderBottom": "#ffa0a0a0,1",

        "paddingRight": "2",
        "iconLocation": "leftSide",
        "border": "#ff313539,1",
        "selectedForeground": "#ffffffff",
        "iconAlignment": "center",
        "foreground": "#ff555555",
        "inactiveForeground": "#ff808080",
        "textAlignment": "center",
        "selectedBackground": "#ff696969",
        "lineAlignment": "center",
        "inactiveBackground": "#ffd3d3d3",
        "iconOffset": "0",
        "iconPadding": "0",
        "contentFit": "auto",
        "paddingTop": "2",
        "shapeBackground": "#ff008e00",
        "paddingBottom": "2",
        "iconIndex": "0",
        "head": {
            "background2": "linear,#ffe9f0f8,#ffc3d8f1,90",
            "selectedBackground2": "#ff696969",
            "foreground2": "#ff000000",
            "selectedForeground2": "#ffffffff",
            "borderBottom2": "#ff5d8cc9,1",
            "borderTop2": "#ffffffff,1",
            "borderLeft2": "#ffffffff,1",
            "borderRight2": "#ff5d8cc9,1",

            "iconLocation": "leftSide",
            "border": "#ff000000,0",
            "iconAlignment": "center",
            "contentFit": "auto",
            "inactiveBackground": "#ffd3d3d3",
            "iconOffset": "0",
            "iconPadding": "0",
            "shapeBackground": "#ff008e00",
            "paddingBottom": "2",
            "paddingTop": "2",
            "paddingRight": "2",
            "inactiveForeground": "#ff808080",
            "textAlignment": "center",
            "lineAlignment": "center",
            "iconIndex": "0"
        }
    },
    "selection": {
        "background": "#10000000",
        "border": "#90000000,1"
    },
    "tree": {
        "expander": {
            "borderRight": null
        }
    }
};